"  todo:
"  - print the settings configured in this file to screen for a visual check when starting
"  - add remap erase by word --> [insert mode] ctrl-w
"  - add remap erase by line --> [insert mode] ctrl-u
"  - add swap buffer places shortcut
"  - add alternate ctrl-[ key

" troubleshooting:
" - verify what the setting is currently set to with: :verbose set autoindent?

" pathogen plugin manager {
    execute pathogen#infect()
" }


" color {
    " color space
    set t_Co=256
    let base16colorspace=256
    
    colorscheme gruvbox
    set background=dark

    syntax on
" }


" copy/paste {
    " paste to clipboard
    set clipboard+=unnamed
    " set the paste environment
    set paste
" }

" search {
	" highlight all search results
	set hlsearch
" }

" file manager {
    " nerdtree
        " open nerdtree at directory
        " autocmd VimEnter * NERDTree /home/j6ck6l/dev
        autocmd VimEnter * NERDTree
        autocmd VimEnter * wincmd p
        map <C-n> :NERDTreeToggle<CR>
        map <Leader>n <plug>NERDTreeTabsToggle<CR>
        let NERDTreeShowHidden=1
" }

" buffer control {
    map <S-J> :bprev<CR>
    map <S-K> :bnext<CR>
    map <C-h> <C-W>h
    map <C-l> <C-W>l
    map <C-I> <C-[>
" }

" set font style outside of a terminal environment (gui) {
   if has("gui_running")
       "  macos
       if has(“gui_macvim")
       		set guifont=Source\ Code\ Pro:h13
	   "  linux
       elseif has(“gui_gtk2")
       		set guifont=Inconsolata\ 12
       endif
   endif
" }

" vim-bufferline {
   " show buffer numbers
   let g:bufferline_show_bufnr = 1
   " scroll with fix current buffer position
   let g:bufferline_rotate = 1
" }

" vim-airline {
   let g:airline#extensions#tabline#enabled = 1
   let g:airline#extensions#wordcount#enabled = 1
   " remove the utf-8
   let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'
   " show only the filename
   let g:airline#extensions#tabline#fnamemod = ':t'
" }

" scroll {
	" center cursor
	set scrolloff=999
	" toggle center cursor
	nnoremap <Leader>zz :let &scrolloff=999-&scrolloff<CR>
	" map \\ and \hl to highlight search results
	nmap <Leader>hl :set hls!<CR>
	nmap <Leader>\  :set hls!<CR>
	" remove current highlights on search
	nnoremap / :set hlsearch<CR>/
" }

" display {
    set number
    set ruler
    set laststatus=2
    set cursorline
    set ignorecase
" }

" indent {
    " translate \t to pipe char | 
    set listchars=tab:\|\
    set list
" }

" Format {
    " use a mixture of spaces & tabs.
    set tabstop=4
    " amount of column intendations that will be used when moving blocks of text forward and backward in visual mode
    set shiftwidth=4
    " auto indent after /n
    set autoindent
    " detect file type for language specific indentation - filetype on / plugin on / indent on
    filetype plugin indent on
" }
