#!/opt/homebrew/bin/bash

if [[ -d "/opt/homebrew/bin" ]]; then 
	export PATH="/opt/homebrew/bin:$PATH"
fi

export PATH="/Users/jack/Library/Python/3.9/bin:$PATH"
# export TERM=xterm-256color
export PS1='\[\033[01;32m\]\u@\h:\[\033[01;34m\]\w\$\[\033[0m\] '

# alias / shortcut {
	alias l='ls -Ga'
	alias ll='ls -Glah'
	alias ls='ls -G'
	alias ..='cd ..'
# }

# functions {

	# tool retrieval from toolbox (tb)
	# usage: tb <tool-name>.tool
	tb() {
		if [[ -z "${1}" ]]; then
			echo "Usage: tb <tool>"
			return 1
		fi
		spinner
		local TOOL="${1}"
		local TOOLBOX="${XDG_DATA_HOME:-$HOME/.local/share}/toolbox/bash.toolbox"
		if [[ -f ${TOOLBOX} ]]; then
			awk "/#@ $TOOL.tool/,/@#/" "${TOOLBOX}"
			else
				echo "Toolbox not found at: ${TOOLBOX}"
		fi
		echo "               "
		echo "[+] ^^^"
		echo "               "
	}

	spinner() {
		local spinarr=('/' '-' '\' '|')  # array of characters
		local delay=0.1
		local i c
		for i in $(seq 1 30); do
			c="${spinarr[$((i % 4))]}"   # cycle through array
			printf "\r[%s] Searching toolbox" "$c"
			sleep "$delay"
		done
		printf "\r                     \n"
		# printf "[+] Toolbox ^^^         \n"
		printf "[+] ^^^ Toolbox        \n"
		echo "               "
	}
#}















